# Generated by Django 4.2.5 on 2023-12-17 13:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='link_1',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='link_2',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='link_3',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='link_4',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='link_5',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='link_6',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='link_7',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='link_8',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='photo_1',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='photo_2',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='photo_3',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='photo_4',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='photo_5',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='photo_6',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='photo_7',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='photo_8',
        ),
        migrations.CreateModel(
            name='SportsAchievements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photos/')),
                ('caption', models.CharField(max_length=255)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SocialActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photos/')),
                ('caption', models.CharField(max_length=255)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalAchievements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photos/')),
                ('caption', models.CharField(max_length=255)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CreativeAchievements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photos/')),
                ('caption', models.CharField(max_length=255)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AcademicAchievements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photos/')),
                ('caption', models.CharField(max_length=255)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
