# Generated by Django 4.2.5 on 2023-12-17 13:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('people', '0002_remove_portfolio_link_1_remove_portfolio_link_2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academicachievements',
            name='caption',
        ),
        migrations.RemoveField(
            model_name='creativeachievements',
            name='caption',
        ),
        migrations.RemoveField(
            model_name='personalachievements',
            name='caption',
        ),
        migrations.RemoveField(
            model_name='socialactivity',
            name='caption',
        ),
        migrations.RemoveField(
            model_name='sportsachievements',
            name='caption',
        ),
        migrations.AlterField(
            model_name='academicachievements',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='creativeachievements',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='personalachievements',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='socialactivity',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sportsachievements',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
