# Generated by Django 4.2.5 on 2023-12-17 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_remove_academicachievements_caption_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalachievements',
            name='user',
        ),
        migrations.RemoveField(
            model_name='socialactivity',
            name='user',
        ),
        migrations.RemoveField(
            model_name='sportsachievements',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='academicachievements',
            options={'ordering': ['-creation_date', 'user'], 'verbose_name': 'Академические достижения', 'verbose_name_plural': 'Академические достижения'},
        ),
        migrations.AlterField(
            model_name='academicachievements',
            name='creation_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.DeleteModel(
            name='CreativeAchievements',
        ),
        migrations.DeleteModel(
            name='PersonalAchievements',
        ),
        migrations.DeleteModel(
            name='SocialActivity',
        ),
        migrations.DeleteModel(
            name='SportsAchievements',
        ),
    ]
