# Generated by Django 4.2.5 on 2023-12-28 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0005_category_academicachievements_cat'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='academicachievements',
            options={'ordering': ['-creation_date', 'user'], 'verbose_name': 'Достижения', 'verbose_name_plural': 'Достижения'},
        ),
        migrations.AddField(
            model_name='academicachievements',
            name='description',
            field=models.TextField(blank=True, max_length=765),
        ),
    ]
