# Generated by Django 4.2.5 on 2023-12-28 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0006_alter_academicachievements_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicachievements',
            name='cat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='people.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='academicachievements',
            name='description',
            field=models.TextField(blank=True, max_length=765, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='academicachievements',
            name='image',
            field=models.ImageField(upload_to='photos/', verbose_name='Подтверждение'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='description',
            field=models.TextField(max_length=1765, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='skills',
            field=models.CharField(max_length=255, verbose_name='Навыки'),
        ),
    ]
